function dxd = dxdFunc(t)
%DXDFUNC
%    DXD = DXDFUNC(T)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    10-Dec-2019 03:50:36

t2 = t.*pi;
dxd = [pi.*sin(t2).*(1.0./4.0);pi.*cos(t2).*(1.0./4.0);0.0;0.0;0.0;pi.*cos(t.*pi.*(1.0./2.4e1)).*(1.0./2.4e1)];
