function [limJun,limJunParc] = limJunFunc(t1,t2,t3)
%LIMJUNFUNC
%    [LIMJUN,LIMJUNPARC] = LIMJUNFUNC(T1,T2,T3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    11-Dec-2019 03:42:11

t5 = t3+pi;
t6 = 1.0./pi.^2;
limJun = t1.^2.*t6.*(-1.0./9.6e1)-t2.^2.*t6.*(1.0./6.0)-t5.^2.*t6.*(1.0./6.0);
if nargout > 1
    limJunParc = [t1.*t6.*(-1.0./4.8e1);t2.*t6.*(-1.0./3.0);t6.*(t3.*2.0+pi.*2.0).*(-1.0./6.0)];
end
