function x_cd = x_cdFunc(t)
%X_CDFUNC
%    X_CD = X_CDFUNC(T)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    11-Dec-2019 21:41:36

t2 = t.*(3.0./2.0);
x_cd = [sin(t).*6.0e1+sin(t2).*6.0e1+3.0e2;sin(t+8.0./5.0).*6.0e1+sin(t2+8.0./5.0).*6.0e1+2.0e2];
